const DEFAULT_DURATION = 30;

export const EXHIBIT_TRACKS = {
    E1: {
        url: require('../../../../shared/assets/sound/exhibites/1.mp3'),
        title: 'track_1',
        artist: 'track_1',
        duration: DEFAULT_DURATION,
    },
    E2: {
        url: require('../../../../shared/assets/sound/exhibites/2.mp3'),
        title: 'track_2',
        artist: 'track_2',
        duration: DEFAULT_DURATION,
    },
    E3: {
        url: require('../../../../shared/assets/sound/exhibites/3.mp3'),
        title: 'track_3',
        artist: 'track_3',
        duration: DEFAULT_DURATION,
    },
    E4: {
        url: require('../../../../shared/assets/sound/exhibites/4.mp3'),
        title: 'track_4',
        artist: 'track_4',
        duration: DEFAULT_DURATION,
    },
    E5: {
        url: require('../../../../shared/assets/sound/exhibites/5.mp3'),
        title: 'track_5',
        artist: 'track_5',
        duration: DEFAULT_DURATION,
    },
    E6: {
        url: require('../../../../shared/assets/sound/exhibites/6.mp3'),
        title: 'track_6',
        artist: 'track_6',
        duration: DEFAULT_DURATION,
    },
    E7: {
        url: require('../../../../shared/assets/sound/exhibites/7.mp3'),
        title: 'track_7',
        artist: 'track_7',
        duration: DEFAULT_DURATION,
    },
    E8: {
        url: require('../../../../shared/assets/sound/exhibites/8.mp3'),
        title: 'track_8',
        artist: 'track_8',
        duration: DEFAULT_DURATION,
    },
    E9: {
        url: require('../../../../shared/assets/sound/exhibites/9.mp3'),
        title: 'track_9',
        artist: 'track_9',
        duration: DEFAULT_DURATION,
    },
    E10: {
        url: require('../../../../shared/assets/sound/exhibites/10.mp3'),
        title: 'track_10',
        artist: 'track_10',
        duration: DEFAULT_DURATION,
    },
    E11: {
        url: require('../../../../shared/assets/sound/exhibites/11.mp3'),
        title: 'track_11',
        artist: 'track_11',
        duration: DEFAULT_DURATION,
    },
    E12: {
        url: require('../../../../shared/assets/sound/exhibites/12.mp3'),
        title: 'track_12',
        artist: 'track_12',
        duration: DEFAULT_DURATION,
    },
    E13: {
        url: require('../../../../shared/assets/sound/exhibites/13.mp3'),
        title: 'track_13',
        artist: 'track_13',
        duration: DEFAULT_DURATION,
    },
    E14: {
        url: require('../../../../shared/assets/sound/exhibites/14.mp3'),
        title: 'track_14',
        artist: 'track_14',
        duration: DEFAULT_DURATION,
    },
    E15: {
        url: require('../../../../shared/assets/sound/exhibites/15.mp3'),
        title: 'track_15',
        artist: 'track_15',
        duration: DEFAULT_DURATION,
    },
    E16: {
        url: require('../../../../shared/assets/sound/exhibites/16.mp3'),
        title: 'track_16',
        artist: 'track_16',
        duration: DEFAULT_DURATION,
    },
    E17: {
        url: require('../../../../shared/assets/sound/exhibites/17.mp3'),
        title: 'track_17',
        artist: 'track_17',
        duration: DEFAULT_DURATION,
    },
    E18: {
        url: require('../../../../shared/assets/sound/exhibites/18.mp3'),
        title: 'track_18',
        artist: 'track_18',
        duration: DEFAULT_DURATION,
    },
    E19: {
        url: require('../../../../shared/assets/sound/exhibites/19.mp3'),
        title: 'track_19',
        artist: 'track_19',
        duration: DEFAULT_DURATION,
    },
    E20: {
        url: require('@shared/assets/sound/exhibites/20,67.mp3'),
        title: 'track_20',
        artist: 'track_20',
        duration: DEFAULT_DURATION,
    },
    E21: {
        url: require('../../../../shared/assets/sound/exhibites/21.mp3'),
        title: 'track_21',
        artist: 'track_21',
        duration: DEFAULT_DURATION,
    },
    E22: {
        url: require('../../../../shared/assets/sound/exhibites/22.mp3'),
        title: 'track_22',
        artist: 'track_22',
        duration: DEFAULT_DURATION,
    },
    E23: {
        url: require('../../../../shared/assets/sound/exhibites/23.mp3'),
        title: 'track_23',
        artist: 'track_23',
        duration: DEFAULT_DURATION,
    },
    E24: {
        url: require('../../../../shared/assets/sound/exhibites/24.mp3'),
        title: 'track_24',
        artist: 'track_24',
        duration: DEFAULT_DURATION,
    },
    E25: {
        url: require('../../../../shared/assets/sound/exhibites/25.mp3'),
        title: 'track_25',
        artist: 'track_25',
        duration: DEFAULT_DURATION,
    },
    E26: {
        url: require('../../../../shared/assets/sound/exhibites/26.mp3'),
        title: 'track_26',
        artist: 'track_26',
        duration: DEFAULT_DURATION,
    },
    E27: {
        url: require('../../../../shared/assets/sound/exhibites/27.mp3'),
        title: 'track_27',
        artist: 'track_27',
        duration: DEFAULT_DURATION,
    },
    E28: {
        url: require('../../../../shared/assets/sound/exhibites/28.mp3'),
        title: 'track_28',
        artist: 'track_28',
        duration: DEFAULT_DURATION,
    },
    E29: {
        url: require('../../../../shared/assets/sound/exhibites/29.mp3'),
        title: 'track_29',
        artist: 'track_29',
        duration: DEFAULT_DURATION,
    },
    E30: {
        url: require('../../../../shared/assets/sound/exhibites/30.mp3'),
        title: 'track_30',
        artist: 'track_30',
        duration: DEFAULT_DURATION,
    },
    E31: {
        url: require('../../../../shared/assets/sound/exhibites/31.mp3'),
        title: 'track_31',
        artist: 'track_31',
        duration: DEFAULT_DURATION,
    },
    E32: {
        url: require('../../../../shared/assets/sound/exhibites/32.mp3'),
        title: 'track_32',
        artist: 'track_32',
        duration: DEFAULT_DURATION,
    },
    E33: {
        url: require('../../../../shared/assets/sound/exhibites/33.mp3'),
        title: 'track_33',
        artist: 'track_33',
        duration: DEFAULT_DURATION,
    },
    E34: {
        url: require('../../../../shared/assets/sound/exhibites/34.mp3'),
        title: 'track_34',
        artist: 'track_34',
        duration: DEFAULT_DURATION,
    },
    E35: {
        url: require('../../../../shared/assets/sound/exhibites/35.mp3'),
        title: 'track_35',
        artist: 'track_35',
        duration: DEFAULT_DURATION,
    },
    E36: {
        url: require('@shared/assets/sound/exhibites/36,41.mp3'),
        title: 'track_36',
        artist: 'track_36',
        duration: DEFAULT_DURATION,
    },
    E37: {
        url: require('../../../../shared/assets/sound/exhibites/37,40.mp3'),
        title: 'track_37',
        artist: 'track_37',
        duration: DEFAULT_DURATION,
    },
    E38: {
        url: require('../../../../shared/assets/sound/exhibites/38,39.mp3'),
        title: 'track_38',
        artist: 'track_38',
        duration: DEFAULT_DURATION,
    },
    E39: {
        url: require('../../../../shared/assets/sound/exhibites/38,39.mp3'),
        title: 'track_39',
        artist: 'track_39',
        duration: DEFAULT_DURATION,
    },
    E40: {
        url: require('../../../../shared/assets/sound/exhibites/37,40.mp3'),
        title: 'track_40',
        artist: 'track_40',
        duration: DEFAULT_DURATION,
    },
    E41: {
        url: require('../../../../shared/assets/sound/exhibites/36,41.mp3'),
        title: 'track_41',
        artist: 'track_41',
        duration: DEFAULT_DURATION,
    },
    E42: {
        url: require('../../../../shared/assets/sound/exhibites/42.mp3'),
        title: 'track_42',
        artist: 'track_42',
        duration: DEFAULT_DURATION,
    },
    E43: {
        url: require('../../../../shared/assets/sound/exhibites/43.mp3'),
        title: 'track_43',
        artist: 'track_43',
        duration: DEFAULT_DURATION,
    },
    E44: {
        url: require('../../../../shared/assets/sound/exhibites/44.mp3'),
        title: 'track_44',
        artist: 'track_44',
        duration: DEFAULT_DURATION,
    },
    E45: {
        url: require('../../../../shared/assets/sound/exhibites/45.mp3'),
        title: 'track_45',
        artist: 'track_45',
        duration: DEFAULT_DURATION,
    },
    E46: {
        url: require('../../../../shared/assets/sound/exhibites/46.mp3'),
        title: 'track_46',
        artist: 'track_46',
        duration: DEFAULT_DURATION,
    },
    // No record
    // E47: {
    //     url: require('../../../../shared/assets/sound/exhibites/47.mp3'),
    //     title: 'track_47',
    //     artist: 'track_47',
    //     duration: DEFAULT_DURATION,
    // },
    E48: {
        url: require('../../../../shared/assets/sound/exhibites/48.mp3'),
        title: 'track_48',
        artist: 'track_48',
        duration: DEFAULT_DURATION,
    },
    E49: {
        url: require('../../../../shared/assets/sound/exhibites/49.mp3'),
        title: 'track_49',
        artist: 'track_49',
        duration: DEFAULT_DURATION,
    },
    E50: {
        url: require('../../../../shared/assets/sound/exhibites/50.mp3'),
        title: 'track_50',
        artist: 'track_50',
        duration: DEFAULT_DURATION,
    },
    E51: {
        url: require('../../../../shared/assets/sound/exhibites/51.mp3'),
        title: 'track_51',
        artist: 'track_51',
        duration: DEFAULT_DURATION,
    },
    E52: {
        url: require('../../../../shared/assets/sound/exhibites/52.mp3'),
        title: 'track_52',
        artist: 'track_52',
        duration: DEFAULT_DURATION,
    },
    E53: {
        url: require('../../../../shared/assets/sound/exhibites/53.mp3'),
        title: 'track_53',
        artist: 'track_53',
        duration: DEFAULT_DURATION,
    },
    E54: {
        url: require('../../../../shared/assets/sound/exhibites/54.mp3'),
        title: 'track_54',
        artist: 'track_54',
        duration: DEFAULT_DURATION,
    },
    E55: {
        url: require('../../../../shared/assets/sound/exhibites/55.mp3'),
        title: 'track_55',
        artist: 'track_55',
        duration: DEFAULT_DURATION,
    },
    E56: {
        url: require('../../../../shared/assets/sound/exhibites/56.mp3'),
        title: 'track_56',
        artist: 'track_56',
        duration: DEFAULT_DURATION,
    },
    E57: {
        url: require('../../../../shared/assets/sound/exhibites/57.mp3'),
        title: 'track_57',
        artist: 'track_57',
        duration: DEFAULT_DURATION,
    },
    E58: {
        url: require('../../../../shared/assets/sound/exhibites/58.mp3'),
        title: 'track_58',
        artist: 'track_58',
        duration: DEFAULT_DURATION,
    },
    E59: {
        url: require('../../../../shared/assets/sound/exhibites/59.mp3'),
        title: 'track_59',
        artist: 'track_59',
        duration: DEFAULT_DURATION,
    },
    E60: {
        url: require('../../../../shared/assets/sound/exhibites/60.mp3'),
        title: 'track_60',
        artist: 'track_60',
        duration: DEFAULT_DURATION,
    },
    E61: {
        url: require('../../../../shared/assets/sound/exhibites/61.mp3'),
        title: 'track_61',
        artist: 'track_61',
        duration: DEFAULT_DURATION,
    },
    E62: {
        url: require('../../../../shared/assets/sound/exhibites/62.mp3'),
        title: 'track_62',
        artist: 'track_62',
        duration: DEFAULT_DURATION,
    },
    E63: {
        url: require('../../../../shared/assets/sound/exhibites/63.mp3'),
        title: 'track_63',
        artist: 'track_63',
        duration: DEFAULT_DURATION,
    },
    E64: {
        url: require('../../../../shared/assets/sound/exhibites/64.mp3'),
        title: 'track_64',
        artist: 'track_64',
        duration: DEFAULT_DURATION,
    },
    E65: {
        url: require('../../../../shared/assets/sound/exhibites/65.mp3'),
        title: 'track_65',
        artist: 'track_65',
        duration: DEFAULT_DURATION,
    },
    E66: {
        url: require('../../../../shared/assets/sound/exhibites/66.mp3'),
        title: 'track_66',
        artist: 'track_66',
        duration: DEFAULT_DURATION,
    },
    E67: {
        url: require('../../../../shared/assets/sound/exhibites/20,67.mp3'),
        title: 'track_67',
        artist: 'track_67',
        duration: DEFAULT_DURATION,
    },
    E68: {
        url: require('../../../../shared/assets/sound/exhibites/68.mp3'),
        title: 'track_68',
        artist: 'track_68',
        duration: DEFAULT_DURATION,
    },
};
