export enum ARTICLE_IDS {
    // GORO_NUDO_MASAMUNE = 'goro_nudo_masamune',
    // SAKAI = 'sakai',
    // HIKOSIRO_SADAMUNE = 'hikosiro_masamune',
    NOBUNAGA_ODA = 'NOBUNAGA_ODA',
    TOETOMI_HIDEOSI = 'TOETOMI_HIDEOSI',
    TOKUGAWA_IEYASU = 'TOKUGAWA_IEYASU',
    SAKAI_CLAN = 'SAKAI_CLAN',
    HATORI_HANDZO = 'HATORI_HANDZO',
    TADAKATSU_HONDA = 'TADAKATSU_HONDA',
    THREE_GREAT_SPEARS = 'THREE_GREAT_SPEARS',
    TAKEDA_SINGEN = 'TAKEDA_SINGEN',
}
